# Generated by Django 4.1.7 on 2023-04-02 06:21

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('url', models.URLField()),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_active'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='FooterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Your phone number', max_length=128, region=None)),
                ('email', models.EmailField(help_text='Your e-mail address', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('twitter', 'Twitter')], help_text='Social network name', max_length=20)),
                ('url', models.URLField(help_text='Your account URL')),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('40.8154,72.2837', 'Andijon'), ('39.7681,64.4556', 'Buxoro'), ('40.3734,71.7978', "Farg'ona"), ('40.1250,67.8808', 'Jizzax'), ('41.0058,71.6436', 'Namangan'), ('40.1039,65.3688', 'Navoiy'), ('42.4619,59.6166', 'Nukus'), ('38.8612,65.7847', 'Qarshi'), ('39.6508,66.9654', 'Samarqand'), ('40.8373,68.6618', 'Sirdaryo'), ('37.2611,67.3086', 'Termiz'), ('41.2995,69.2401', 'Toshkent'), ('41.2213,69.8597', 'Toshkent vil'), ('41.3565,60.8567', 'Xorazm')], max_length=30)),
                ('temp', models.FloatField()),
                ('text', models.CharField(max_length=20)),
                ('icon', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
