# Generated by Django 4.1.7 on 2023-03-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('url', models.URLField()),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
