# Generated by Django 4.1.7 on 2023-03-26 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_add'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add',
            options={'ordering': ['is_active']},
        ),
    ]
