# Generated by Django 4.1.7 on 2023-03-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='city',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='location',
            field=models.CharField(choices=[('40.8154,72.2837', 'Andijon'), ('39.7681,64.4556', 'Buxoro'), ('40.3734,71.7978', "Farg'ona"), ('40.1250,67.8808', 'Jizzax'), ('41.0058,71.6436', 'Namangan'), ('40.1039,65.3688', 'Navoiy'), ('42.4619,59.6166', 'Nukus'), ('38.8612,65.7847', 'Qarshi'), ('39.6508,66.9654', 'Samarqand'), ('40.8373,68.6618', 'Sirdaryo'), ('37.2611,67.3086', 'Termiz'), ('41.2995,69.2401', 'Toshkent'), ('41.2213,69.8597', 'Toshkent vil'), ('41.3565,60.8567', 'Xorazm')], max_length=30),
        ),
    ]
