# Generated by Django 4.1.7 on 2023-03-29 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_weather_city_alter_weather_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='city',
        ),
    ]
