# Generated by Django 4.1.7 on 2023-03-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_weather_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('twitter', 'Twitter')], help_text='Social network name', max_length=20)),
                ('url', models.URLField(help_text='Your account URL')),
            ],
        ),
    ]
