# Generated by Django 4.1.7 on 2023-03-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_socialaccounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialaccounts',
            options={'verbose_name': 'Social Account', 'verbose_name_plural': 'Social Accounts'},
        ),
    ]
