# Generated by Django 4.1.7 on 2023-03-30 04:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_socialaccounts_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Your phone number', max_length=128, region=None)),
                ('email', models.EmailField(help_text='Your e-mail address', max_length=254)),
            ],
        ),
    ]
